export const PLANS = {
  free: {
    name: "Free",
    price: 0,
    planId: null,
    description: "Get started with basic market data",
    features: [
      "5 tracked assets",
      "Delayed prices (15 min)",
      "Basic economic calendar",
      "Limited news feed",
    ],
    limits: ["No AI Briefing", "No Trump Monitor", "No Session Intelligence"],
  },
  pro: {
    name: "Pro",
    price: 29,
    planId: process.env.NEXT_PUBLIC_PAYPAL_PRO_PLAN_ID ?? "",
    description: "Full terminal for serious traders",
    features: [
      "All assets (Gold, Forex, Crypto, Indices)",
      "Real-time live prices",
      "Full economic calendar + analysis",
      "AI Market Briefing",
      "Trump Monitor",
      "Session Intelligence",
      "Catalysts feed",
      "Market Bias engine",
    ],
    limits: [],
  },
  elite: {
    name: "Elite",
    price: 99,
    planId: process.env.NEXT_PUBLIC_PAYPAL_ELITE_PLAN_ID ?? "",
    description: "Maximum edge for professional traders",
    features: [
      "Everything in Pro",
      "Priority data feeds",
      "Advanced AI analysis",
      "Asset Matrix",
      "Custom alerts",
      "Mobile APK access",
      "Priority support",
      "Early access to new features",
    ],
    limits: [],
  },
} as const;
