export const PLANS = {
  free: {
    name: "Free",
    price: 0,
    planId: null,
    description: "Get started with basic market data",
    features: [
      "5 tracked assets",
      "Delayed prices (15 min)",
      "Basic economic calendar",
      "Limited news feed",
    ],
    limits: ["No AI Briefing", "No Trump Monitor", "No Session Intelligence"],
  },
  pro: {
    name: "Pro",
    monthlyPrice: 39,
    annualPrice: 399,
    planId: process.env.NEXT_PUBLIC_PAYPAL_PRO_PLAN_ID ?? "",
    annualPlanId: process.env.NEXT_PUBLIC_PAYPAL_PRO_ANNUAL_PLAN_ID ?? "",
    description: "Full terminal for serious traders",
    features: [
      "All assets (Gold, Forex, Crypto, Indices)",
      "Real-time live prices",
      "Full economic calendar + analysis",
      "AI Market Briefing",
      "Trump Monitor",
      "Session Intelligence",
      "Catalysts feed",
      "Market Bias engine",
      "Asset Matrix",
      "Mobile app access",
      "Priority support",
    ],
    limits: [],
  },
} as const;
