export const PLANS = {
  free: {
    name: "Free",
    price: 0,
    planId: null,
    description: "Live prices and essential market tools",
    features: [
      "Live prices — Gold, Forex, Crypto, Indices",
      "TradingView chart",
      "News feed",
      "Economic calendar",
      "Trading signals (view)",
      "Community chat",
      "Trading knowledge base",
    ],
    limits: [
      "No AI analysis",
      "No Market Bias",
      "No Brain Terminal",
      "No Trump Monitor",
      "No PnL Calendar",
    ],
  },
  pro: {
    name: "Pro",
    monthlyPrice: 39,
    annualPrice: 399,
    planId: process.env.NEXT_PUBLIC_PAYPAL_PRO_PLAN_ID ?? "",
    annualPlanId: process.env.NEXT_PUBLIC_PAYPAL_PRO_ANNUAL_PLAN_ID ?? "",
    description: "Full AI-powered terminal for serious traders",
    features: [
      "Everything in Free",
      "Brain Terminal — 7 AI agents",
      "Market Bias engine",
      "Market Intelligence",
      "Asset Matrix",
      "Session Intelligence",
      "AI Catalysts feed",
      "Trump Monitor",
      "PnL Calendar",
      "Candle Analysis (AI)",
      "AI Market Briefing",
      "Force-refresh signals",
    ],
    limits: [],
  },
} as const;
